### ISSUE TITLE
SaslErrorException on trying to run the server

### ISSUE THREAD

**Issue by ghanendrapiplani** [carlosCharz/fcmxmppserverv2#13]
Hi, i cloned your server and tried running it in netbeans. However i am getting the following exception:
`org.jivesoftware.smack.sasl.SASLErrorException: SASLError using PLAIN: not-authorized
	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:290)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1082)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:980)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:996)
	at java.lang.Thread.run(Thread.java:745)
`

I am using the project_id and web api key i found from the Firebase console of the app. Please help me figure out the solution to this.
thanks.

**Comment by carlosCharz** [comment]
First approach. I do not think it is about due to netbeans. Possible solutions: 1. check carefully the parameters for the connection. 2. Check in the server you are using if there is no issue related to the firewall or something that blocks the connection. 3. First run it in localhost or as a jar to make sure it works first.

**Comment by luucasgoomes** [comment]
Hi guys, I faced the same problem, and I'm running as a jar. I'm sure that is no relation with the credentials because I tested with an http server. 
ghanendrapiplani -> Make sure that the credentials that you are using are from the cloud messaging part in configurations, and not in General. 
If you guys found the solution contact me! Thanks

**Comment by luucasgoomes** [comment]
Hello Guys, 
I was using the wrong id parameter. I was using the "Project ID" from General Options and the correct one is in the Cloud Messaging!
